package com.urjc.daw.ViewsControllers;

import com.urjc.daw.Models.User.User;
import com.urjc.daw.Models.User.UserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller
public class IndexController {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    @RequestMapping(path="/login") // Map ONLY GET Requests
    public String login () {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        //User n = new User(name,"",email,"");
        //n.setName(name);
        //n.setEmail(email);
        //System.out.println(name);
        //System.out.println(email);
        //userRepository.save(n);
        return "login";
    }



}
